source 'http://rubygems.org'

gem 'rails', '3.1.1'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.1.4'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

gem 'rails-dev-tweaks', '~> 0.5.1'
gem 'letter_opener', :group => :development

gem "rspec-rails", :group => [:test, :development]

gem 'faker'

group :test do
  gem 'turn', :require => false # Pretty printed test output
  gem "mocha"
  gem "factory_girl_rails"
  gem "capybara"
  gem "guard-rspec"
  gem "spork", "> 0.9.0.rc"
  gem "guard-spork"
  gem "escape_utils"
#  gem 'simplecov', '>= 0.4.0', :require => false
end

# Gemfiles added by Ben
gem 'execjs'
gem 'therubyracer', :platforms => :ruby